version: "3"

services:
  database:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_DB=pos_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_ROOT_PASSWORD=root
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db_vol:/var/lib/postgres

  test_database:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_DB=test_pos_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_ROOT_PASSWORD=root
    ports:
      - '5431:5432'
    expose:
      - '5431'
    volumes:
      - test_db_vol:/var/lib/postgres

volumes:
  db_vol:
  test_db_vol:
